### PR TITLE
Add setting to Vagrantfile

### PR DESCRIPTION
**Pull request by ofirtzabari**
Added a setting to run bootstrap.sh when the VM up fix issue #1

### CODE REVIEW

**Comment by RonTuretzky** [comment]
LGTM

**Review by EliasAndry — APPROVED** [review]

**Review by FaezZangariya — APPROVED** [review]

**Review by EliasAndry — APPROVED** [review]

**Comment by kobihk** [comment]
@ofirtzabari after we merged #16 
Please rebase the PR and push again to make sure the Flake8 check will pass

**Review by RonTuretzky — APPROVED** [review]
LGTM

**Comment by ofirtzabari** [comment]
colesed and open new one

**Pull request closed without merging**
